spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/familyhub
    username: postgres
    password: 210902
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
